<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'TENANT_CREATE_BUTTON' => 'Neuer Mandant',
    'TENANT_FLASH_CREATED' => 'Der Mandant wurde erfolgreich erstellt.',
    'TENANT_FLASH_DELETED' => 'Der Mandant wurde erfolgreich gelöscht.',
    'TENANT_FLASH_UPDATED' => 'Der Mandant wurde erfolgreich aktualisiert.',
    'TENANT_LABEL_LANGUAGE' => 'Sprache',
    'TENANT_LABEL_NAME' => 'Name',
    'TENANT_LABEL_URL' => 'URL',
    'TENANT_NAME' => 'Mandant',
    'TENANT_NAME_PLURAL' => 'Mandanten',
    'TENANT_SWITCH_ADMIN_BUTTON' => 'Zu Mandant wechseln',
    'TENANT_TITLE_CREATE' => 'Neuen Mandant erstellen',
    'TENANT_TITLE_DELETE' => 'Mandant löschen',
    'TENANT_TITLE_UPDATE' => 'Mandant bearbeiten',
    'TENANT_ERROR_PATH_PROTECTED' => 'Die URL "{path}" ist geschützt.',
];
