#!/usr/bin/env php
<?php

declare(strict_types=1);

use Hirtz\Skeleton\console\Application;

defined('YII_ENV') or define('YII_ENV', 'test');
defined('YII_DEBUG') or define('YII_DEBUG', true);

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

exit((new Application(require(__DIR__ . '/config.php')))->run());
