<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'TENANT_CREATE_BUTTON' => '',
    'TENANT_ERROR_PATH_PROTECTED' => '',
    'TENANT_FLASH_CREATED' => '',
    'TENANT_FLASH_DELETED' => '',
    'TENANT_FLASH_UPDATED' => '',
    'TENANT_HINT_COOKIE_DOMAIN' => '',
    'TENANT_LABEL_COOKIE_DOMAIN' => '',
    'TENANT_LABEL_LANGUAGE' => '',
    'TENANT_LABEL_NAME' => '',
    'TENANT_LABEL_URL' => '',
    'TENANT_NAME' => '',
    'TENANT_NAME_PLURAL' => '',
    'TENANT_SWITCH_ADMIN_BUTTON' => '',
    'TENANT_TITLE_CREATE' => '',
    'TENANT_TITLE_DELETE' => '',
    'TENANT_TITLE_UPDATE' => '',
];
