<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'TENANT_AUTH_CREATE' => 'Create tenants',
    'TENANT_AUTH_DELETE' => 'Delete tenants',
    'TENANT_AUTH_UPDATE' => 'Update tenants',
    'TENANT_CREATE_BUTTON' => 'New Tenant',
    'TENANT_ERROR_DELETE_LAST' => 'This is the only tenant and thus cannot be deleted.',
    'TENANT_ERROR_DELETE_RELATION' => 'This tenant cannot be deleted because it is linked to other relations.',
    'TENANT_ERROR_PATH_PROTECTED' => 'The URL "{path}" is protected.',
    'TENANT_FLASH_CREATED' => 'Tenant has been created.',
    'TENANT_FLASH_DELETED' => 'Tenant has been deleted.',
    'TENANT_FLASH_UPDATED' => 'Tenant has been updated.',
    'TENANT_LABEL_COOKIE_DOMAIN' => 'Cookie domain',
    'TENANT_LABEL_LANGUAGE' => 'Language',
    'TENANT_LABEL_NAME' => 'Name',
    'TENANT_LABEL_URL' => 'URL',
    'TENANT_NAME' => 'Tenant',
    'TENANT_NAME_PLURAL' => 'Tenants',
    'TENANT_SWITCH_ADMIN_BUTTON' => 'Switch to tenant',
    'TENANT_TITLE_CREATE' => 'Create New Tenant',
    'TENANT_TITLE_DELETE' => 'Delete Tenant',
    'TENANT_TITLE_UPDATE' => 'Update Tenant',
];
